import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { titleApp } from "./constants";
import "./w3.css"
import "./globals.css";
import 'bulma/css/bulma.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: titleApp,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
        <head>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
        </head>
        <body 
          className={inter.className} 
          suppressHydrationWarning={true}>
            {children}
        </body>
    </html>
  );
}
