import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import { AuthContext } from "./context/AuthContext";
//import { useAuth } from "./hooks/useAuth";
import "./globals.css";
import 'bulma/css/bulma.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Visual Studio Code",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const { user, login, logout, setUser } = useAuth();
  return (
    <html lang="en">
        <head>
            <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        </head>
        <body 
          className={inter.className} 
          suppressHydrationWarning={true}>
            {children}
        </body>
    </html>
  );
}
